// ============================================================================
// Complete MOS 6502 opcode table (0x00-0xFF)
// All 256 entries for the NMOS 6502 as used in the Commodore 64
// ============================================================================

import type { OpcodeInfo, AddressingMode, FlowType } from "./types.js";

// Helper to create opcode entries concisely
function op(
  opcode: number,
  mnemonic: string,
  addressingMode: AddressingMode,
  bytes: number,
  cycles: number,
  flowType: FlowType,
  undocumented: boolean,
  readTarget: boolean,
  writeTarget: boolean,
): OpcodeInfo {
  return { opcode, mnemonic, addressingMode, bytes, cycles, flowType, undocumented, readTarget, writeTarget };
}

// Shorthand aliases for common patterns
const seq: FlowType = "sequential";
const br: FlowType = "branch";
const jmp: FlowType = "jump";
const call: FlowType = "call";
const ret: FlowType = "return";
const halt: FlowType = "halt";

export const OPCODE_TABLE: OpcodeInfo[] = [
  // ========================== 0x00-0x0F ==========================
  op(0x00, "brk", "implied",     2, 7, halt, false, false, false),
  op(0x01, "ora", "indirect_x",  2, 6, seq,  false, true,  false),
  op(0x02, "jam", "implied",     1, 0, halt, true,  false, false),
  op(0x03, "slo", "indirect_x",  2, 8, seq,  true,  true,  true),
  op(0x04, "nop", "zero_page",   2, 3, seq,  true,  true,  false),
  op(0x05, "ora", "zero_page",   2, 3, seq,  false, true,  false),
  op(0x06, "asl", "zero_page",   2, 5, seq,  false, true,  true),
  op(0x07, "slo", "zero_page",   2, 5, seq,  true,  true,  true),
  op(0x08, "php", "implied",     1, 3, seq,  false, false, false),
  op(0x09, "ora", "immediate",   2, 2, seq,  false, false, false),
  op(0x0a, "asl", "accumulator", 1, 2, seq,  false, false, false),
  op(0x0b, "anc", "immediate",   2, 2, seq,  true,  false, false),
  op(0x0c, "nop", "absolute",    3, 4, seq,  true,  true,  false),
  op(0x0d, "ora", "absolute",    3, 4, seq,  false, true,  false),
  op(0x0e, "asl", "absolute",    3, 6, seq,  false, true,  true),
  op(0x0f, "slo", "absolute",    3, 6, seq,  true,  true,  true),

  // ========================== 0x10-0x1F ==========================
  op(0x10, "bpl", "relative",    2, 2, br,   false, false, false),
  op(0x11, "ora", "indirect_y",  2, 5, seq,  false, true,  false),
  op(0x12, "jam", "implied",     1, 0, halt, true,  false, false),
  op(0x13, "slo", "indirect_y",  2, 8, seq,  true,  true,  true),
  op(0x14, "nop", "zero_page_x", 2, 4, seq,  true,  true,  false),
  op(0x15, "ora", "zero_page_x", 2, 4, seq,  false, true,  false),
  op(0x16, "asl", "zero_page_x", 2, 6, seq,  false, true,  true),
  op(0x17, "slo", "zero_page_x", 2, 6, seq,  true,  true,  true),
  op(0x18, "clc", "implied",     1, 2, seq,  false, false, false),
  op(0x19, "ora", "absolute_y",  3, 4, seq,  false, true,  false),
  op(0x1a, "nop", "implied",     1, 2, seq,  true,  false, false),
  op(0x1b, "slo", "absolute_y",  3, 7, seq,  true,  true,  true),
  op(0x1c, "nop", "absolute_x",  3, 4, seq,  true,  true,  false),
  op(0x1d, "ora", "absolute_x",  3, 4, seq,  false, true,  false),
  op(0x1e, "asl", "absolute_x",  3, 7, seq,  false, true,  true),
  op(0x1f, "slo", "absolute_x",  3, 7, seq,  true,  true,  true),

  // ========================== 0x20-0x2F ==========================
  op(0x20, "jsr", "absolute",    3, 6, call, false, false, false),
  op(0x21, "and", "indirect_x",  2, 6, seq,  false, true,  false),
  op(0x22, "jam", "implied",     1, 0, halt, true,  false, false),
  op(0x23, "rla", "indirect_x",  2, 8, seq,  true,  true,  true),
  op(0x24, "bit", "zero_page",   2, 3, seq,  false, true,  false),
  op(0x25, "and", "zero_page",   2, 3, seq,  false, true,  false),
  op(0x26, "rol", "zero_page",   2, 5, seq,  false, true,  true),
  op(0x27, "rla", "zero_page",   2, 5, seq,  true,  true,  true),
  op(0x28, "plp", "implied",     1, 4, seq,  false, false, false),
  op(0x29, "and", "immediate",   2, 2, seq,  false, false, false),
  op(0x2a, "rol", "accumulator", 1, 2, seq,  false, false, false),
  op(0x2b, "anc", "immediate",   2, 2, seq,  true,  false, false),
  op(0x2c, "bit", "absolute",    3, 4, seq,  false, true,  false),
  op(0x2d, "and", "absolute",    3, 4, seq,  false, true,  false),
  op(0x2e, "rol", "absolute",    3, 6, seq,  false, true,  true),
  op(0x2f, "rla", "absolute",    3, 6, seq,  true,  true,  true),

  // ========================== 0x30-0x3F ==========================
  op(0x30, "bmi", "relative",    2, 2, br,   false, false, false),
  op(0x31, "and", "indirect_y",  2, 5, seq,  false, true,  false),
  op(0x32, "jam", "implied",     1, 0, halt, true,  false, false),
  op(0x33, "rla", "indirect_y",  2, 8, seq,  true,  true,  true),
  op(0x34, "nop", "zero_page_x", 2, 4, seq,  true,  true,  false),
  op(0x35, "and", "zero_page_x", 2, 4, seq,  false, true,  false),
  op(0x36, "rol", "zero_page_x", 2, 6, seq,  false, true,  true),
  op(0x37, "rla", "zero_page_x", 2, 6, seq,  true,  true,  true),
  op(0x38, "sec", "implied",     1, 2, seq,  false, false, false),
  op(0x39, "and", "absolute_y",  3, 4, seq,  false, true,  false),
  op(0x3a, "nop", "implied",     1, 2, seq,  true,  false, false),
  op(0x3b, "rla", "absolute_y",  3, 7, seq,  true,  true,  true),
  op(0x3c, "nop", "absolute_x",  3, 4, seq,  true,  true,  false),
  op(0x3d, "and", "absolute_x",  3, 4, seq,  false, true,  false),
  op(0x3e, "rol", "absolute_x",  3, 7, seq,  false, true,  true),
  op(0x3f, "rla", "absolute_x",  3, 7, seq,  true,  true,  true),

  // ========================== 0x40-0x4F ==========================
  op(0x40, "rti", "implied",     1, 6, ret,  false, false, false),
  op(0x41, "eor", "indirect_x",  2, 6, seq,  false, true,  false),
  op(0x42, "jam", "implied",     1, 0, halt, true,  false, false),
  op(0x43, "sre", "indirect_x",  2, 8, seq,  true,  true,  true),
  op(0x44, "nop", "zero_page",   2, 3, seq,  true,  true,  false),
  op(0x45, "eor", "zero_page",   2, 3, seq,  false, true,  false),
  op(0x46, "lsr", "zero_page",   2, 5, seq,  false, true,  true),
  op(0x47, "sre", "zero_page",   2, 5, seq,  true,  true,  true),
  op(0x48, "pha", "implied",     1, 3, seq,  false, false, false),
  op(0x49, "eor", "immediate",   2, 2, seq,  false, false, false),
  op(0x4a, "lsr", "accumulator", 1, 2, seq,  false, false, false),
  op(0x4b, "alr", "immediate",   2, 2, seq,  true,  false, false),
  op(0x4c, "jmp", "absolute",    3, 3, jmp,  false, false, false),
  op(0x4d, "eor", "absolute",    3, 4, seq,  false, true,  false),
  op(0x4e, "lsr", "absolute",    3, 6, seq,  false, true,  true),
  op(0x4f, "sre", "absolute",    3, 6, seq,  true,  true,  true),

  // ========================== 0x50-0x5F ==========================
  op(0x50, "bvc", "relative",    2, 2, br,   false, false, false),
  op(0x51, "eor", "indirect_y",  2, 5, seq,  false, true,  false),
  op(0x52, "jam", "implied",     1, 0, halt, true,  false, false),
  op(0x53, "sre", "indirect_y",  2, 8, seq,  true,  true,  true),
  op(0x54, "nop", "zero_page_x", 2, 4, seq,  true,  true,  false),
  op(0x55, "eor", "zero_page_x", 2, 4, seq,  false, true,  false),
  op(0x56, "lsr", "zero_page_x", 2, 6, seq,  false, true,  true),
  op(0x57, "sre", "zero_page_x", 2, 6, seq,  true,  true,  true),
  op(0x58, "cli", "implied",     1, 2, seq,  false, false, false),
  op(0x59, "eor", "absolute_y",  3, 4, seq,  false, true,  false),
  op(0x5a, "nop", "implied",     1, 2, seq,  true,  false, false),
  op(0x5b, "sre", "absolute_y",  3, 7, seq,  true,  true,  true),
  op(0x5c, "nop", "absolute_x",  3, 4, seq,  true,  true,  false),
  op(0x5d, "eor", "absolute_x",  3, 4, seq,  false, true,  false),
  op(0x5e, "lsr", "absolute_x",  3, 7, seq,  false, true,  true),
  op(0x5f, "sre", "absolute_x",  3, 7, seq,  true,  true,  true),

  // ========================== 0x60-0x6F ==========================
  op(0x60, "rts", "implied",     1, 6, ret,  false, false, false),
  op(0x61, "adc", "indirect_x",  2, 6, seq,  false, true,  false),
  op(0x62, "jam", "implied",     1, 0, halt, true,  false, false),
  op(0x63, "rra", "indirect_x",  2, 8, seq,  true,  true,  true),
  op(0x64, "nop", "zero_page",   2, 3, seq,  true,  true,  false),
  op(0x65, "adc", "zero_page",   2, 3, seq,  false, true,  false),
  op(0x66, "ror", "zero_page",   2, 5, seq,  false, true,  true),
  op(0x67, "rra", "zero_page",   2, 5, seq,  true,  true,  true),
  op(0x68, "pla", "implied",     1, 4, seq,  false, false, false),
  op(0x69, "adc", "immediate",   2, 2, seq,  false, false, false),
  op(0x6a, "ror", "accumulator", 1, 2, seq,  false, false, false),
  op(0x6b, "arr", "immediate",   2, 2, seq,  true,  false, false),
  op(0x6c, "jmp", "indirect",    3, 5, jmp,  false, false, false),
  op(0x6d, "adc", "absolute",    3, 4, seq,  false, true,  false),
  op(0x6e, "ror", "absolute",    3, 6, seq,  false, true,  true),
  op(0x6f, "rra", "absolute",    3, 6, seq,  true,  true,  true),

  // ========================== 0x70-0x7F ==========================
  op(0x70, "bvs", "relative",    2, 2, br,   false, false, false),
  op(0x71, "adc", "indirect_y",  2, 5, seq,  false, true,  false),
  op(0x72, "jam", "implied",     1, 0, halt, true,  false, false),
  op(0x73, "rra", "indirect_y",  2, 8, seq,  true,  true,  true),
  op(0x74, "nop", "zero_page_x", 2, 4, seq,  true,  true,  false),
  op(0x75, "adc", "zero_page_x", 2, 4, seq,  false, true,  false),
  op(0x76, "ror", "zero_page_x", 2, 6, seq,  false, true,  true),
  op(0x77, "rra", "zero_page_x", 2, 6, seq,  true,  true,  true),
  op(0x78, "sei", "implied",     1, 2, seq,  false, false, false),
  op(0x79, "adc", "absolute_y",  3, 4, seq,  false, true,  false),
  op(0x7a, "nop", "implied",     1, 2, seq,  true,  false, false),
  op(0x7b, "rra", "absolute_y",  3, 7, seq,  true,  true,  true),
  op(0x7c, "nop", "absolute_x",  3, 4, seq,  true,  true,  false),
  op(0x7d, "adc", "absolute_x",  3, 4, seq,  false, true,  false),
  op(0x7e, "ror", "absolute_x",  3, 7, seq,  false, true,  true),
  op(0x7f, "rra", "absolute_x",  3, 7, seq,  true,  true,  true),

  // ========================== 0x80-0x8F ==========================
  op(0x80, "nop", "immediate",   2, 2, seq,  true,  false, false),
  op(0x81, "sta", "indirect_x",  2, 6, seq,  false, false, true),
  op(0x82, "nop", "immediate",   2, 2, seq,  true,  false, false),
  op(0x83, "sax", "indirect_x",  2, 6, seq,  true,  false, true),
  op(0x84, "sty", "zero_page",   2, 3, seq,  false, false, true),
  op(0x85, "sta", "zero_page",   2, 3, seq,  false, false, true),
  op(0x86, "stx", "zero_page",   2, 3, seq,  false, false, true),
  op(0x87, "sax", "zero_page",   2, 3, seq,  true,  false, true),
  op(0x88, "dey", "implied",     1, 2, seq,  false, false, false),
  op(0x89, "nop", "immediate",   2, 2, seq,  true,  false, false),
  op(0x8a, "txa", "implied",     1, 2, seq,  false, false, false),
  op(0x8b, "xaa", "immediate",   2, 2, seq,  true,  false, false),
  op(0x8c, "sty", "absolute",    3, 4, seq,  false, false, true),
  op(0x8d, "sta", "absolute",    3, 4, seq,  false, false, true),
  op(0x8e, "stx", "absolute",    3, 4, seq,  false, false, true),
  op(0x8f, "sax", "absolute",    3, 4, seq,  true,  false, true),

  // ========================== 0x90-0x9F ==========================
  op(0x90, "bcc", "relative",    2, 2, br,   false, false, false),
  op(0x91, "sta", "indirect_y",  2, 6, seq,  false, false, true),
  op(0x92, "jam", "implied",     1, 0, halt, true,  false, false),
  op(0x93, "ahx", "indirect_y",  2, 6, seq,  true,  false, true),
  op(0x94, "sty", "zero_page_x", 2, 4, seq,  false, false, true),
  op(0x95, "sta", "zero_page_x", 2, 4, seq,  false, false, true),
  op(0x96, "stx", "zero_page_y", 2, 4, seq,  false, false, true),
  op(0x97, "sax", "zero_page_y", 2, 4, seq,  true,  false, true),
  op(0x98, "tya", "implied",     1, 2, seq,  false, false, false),
  op(0x99, "sta", "absolute_y",  3, 5, seq,  false, false, true),
  op(0x9a, "txs", "implied",     1, 2, seq,  false, false, false),
  op(0x9b, "tas", "absolute_y",  3, 5, seq,  true,  false, true),
  op(0x9c, "shy", "absolute_x",  3, 5, seq,  true,  false, true),
  op(0x9d, "sta", "absolute_x",  3, 5, seq,  false, false, true),
  op(0x9e, "shx", "absolute_y",  3, 5, seq,  true,  false, true),
  op(0x9f, "ahx", "absolute_y",  3, 5, seq,  true,  false, true),

  // ========================== 0xA0-0xAF ==========================
  op(0xa0, "ldy", "immediate",   2, 2, seq,  false, false, false),
  op(0xa1, "lda", "indirect_x",  2, 6, seq,  false, true,  false),
  op(0xa2, "ldx", "immediate",   2, 2, seq,  false, false, false),
  op(0xa3, "lax", "indirect_x",  2, 6, seq,  true,  true,  false),
  op(0xa4, "ldy", "zero_page",   2, 3, seq,  false, true,  false),
  op(0xa5, "lda", "zero_page",   2, 3, seq,  false, true,  false),
  op(0xa6, "ldx", "zero_page",   2, 3, seq,  false, true,  false),
  op(0xa7, "lax", "zero_page",   2, 3, seq,  true,  true,  false),
  op(0xa8, "tay", "implied",     1, 2, seq,  false, false, false),
  op(0xa9, "lda", "immediate",   2, 2, seq,  false, false, false),
  op(0xaa, "tax", "implied",     1, 2, seq,  false, false, false),
  op(0xab, "lax", "immediate",   2, 2, seq,  true,  false, false),
  op(0xac, "ldy", "absolute",    3, 4, seq,  false, true,  false),
  op(0xad, "lda", "absolute",    3, 4, seq,  false, true,  false),
  op(0xae, "ldx", "absolute",    3, 4, seq,  false, true,  false),
  op(0xaf, "lax", "absolute",    3, 4, seq,  true,  true,  false),

  // ========================== 0xB0-0xBF ==========================
  op(0xb0, "bcs", "relative",    2, 2, br,   false, false, false),
  op(0xb1, "lda", "indirect_y",  2, 5, seq,  false, true,  false),
  op(0xb2, "jam", "implied",     1, 0, halt, true,  false, false),
  op(0xb3, "lax", "indirect_y",  2, 5, seq,  true,  true,  false),
  op(0xb4, "ldy", "zero_page_x", 2, 4, seq,  false, true,  false),
  op(0xb5, "lda", "zero_page_x", 2, 4, seq,  false, true,  false),
  op(0xb6, "ldx", "zero_page_y", 2, 4, seq,  false, true,  false),
  op(0xb7, "lax", "zero_page_y", 2, 4, seq,  true,  true,  false),
  op(0xb8, "clv", "implied",     1, 2, seq,  false, false, false),
  op(0xb9, "lda", "absolute_y",  3, 4, seq,  false, true,  false),
  op(0xba, "tsx", "implied",     1, 2, seq,  false, false, false),
  op(0xbb, "las", "absolute_y",  3, 4, seq,  true,  true,  false),
  op(0xbc, "ldy", "absolute_x",  3, 4, seq,  false, true,  false),
  op(0xbd, "lda", "absolute_x",  3, 4, seq,  false, true,  false),
  op(0xbe, "ldx", "absolute_y",  3, 4, seq,  false, true,  false),
  op(0xbf, "lax", "absolute_y",  3, 4, seq,  true,  true,  false),

  // ========================== 0xC0-0xCF ==========================
  op(0xc0, "cpy", "immediate",   2, 2, seq,  false, false, false),
  op(0xc1, "cmp", "indirect_x",  2, 6, seq,  false, true,  false),
  op(0xc2, "nop", "immediate",   2, 2, seq,  true,  false, false),
  op(0xc3, "dcp", "indirect_x",  2, 8, seq,  true,  true,  true),
  op(0xc4, "cpy", "zero_page",   2, 3, seq,  false, true,  false),
  op(0xc5, "cmp", "zero_page",   2, 3, seq,  false, true,  false),
  op(0xc6, "dec", "zero_page",   2, 5, seq,  false, true,  true),
  op(0xc7, "dcp", "zero_page",   2, 5, seq,  true,  true,  true),
  op(0xc8, "iny", "implied",     1, 2, seq,  false, false, false),
  op(0xc9, "cmp", "immediate",   2, 2, seq,  false, false, false),
  op(0xca, "dex", "implied",     1, 2, seq,  false, false, false),
  op(0xcb, "sbx", "immediate",   2, 2, seq,  true,  false, false),
  op(0xcc, "cpy", "absolute",    3, 4, seq,  false, true,  false),
  op(0xcd, "cmp", "absolute",    3, 4, seq,  false, true,  false),
  op(0xce, "dec", "absolute",    3, 6, seq,  false, true,  true),
  op(0xcf, "dcp", "absolute",    3, 6, seq,  true,  true,  true),

  // ========================== 0xD0-0xDF ==========================
  op(0xd0, "bne", "relative",    2, 2, br,   false, false, false),
  op(0xd1, "cmp", "indirect_y",  2, 5, seq,  false, true,  false),
  op(0xd2, "jam", "implied",     1, 0, halt, true,  false, false),
  op(0xd3, "dcp", "indirect_y",  2, 8, seq,  true,  true,  true),
  op(0xd4, "nop", "zero_page_x", 2, 4, seq,  true,  true,  false),
  op(0xd5, "cmp", "zero_page_x", 2, 4, seq,  false, true,  false),
  op(0xd6, "dec", "zero_page_x", 2, 6, seq,  false, true,  true),
  op(0xd7, "dcp", "zero_page_x", 2, 6, seq,  true,  true,  true),
  op(0xd8, "cld", "implied",     1, 2, seq,  false, false, false),
  op(0xd9, "cmp", "absolute_y",  3, 4, seq,  false, true,  false),
  op(0xda, "nop", "implied",     1, 2, seq,  true,  false, false),
  op(0xdb, "dcp", "absolute_y",  3, 7, seq,  true,  true,  true),
  op(0xdc, "nop", "absolute_x",  3, 4, seq,  true,  true,  false),
  op(0xdd, "cmp", "absolute_x",  3, 4, seq,  false, true,  false),
  op(0xde, "dec", "absolute_x",  3, 7, seq,  false, true,  true),
  op(0xdf, "dcp", "absolute_x",  3, 7, seq,  true,  true,  true),

  // ========================== 0xE0-0xEF ==========================
  op(0xe0, "cpx", "immediate",   2, 2, seq,  false, false, false),
  op(0xe1, "sbc", "indirect_x",  2, 6, seq,  false, true,  false),
  op(0xe2, "nop", "immediate",   2, 2, seq,  true,  false, false),
  op(0xe3, "isc", "indirect_x",  2, 8, seq,  true,  true,  true),
  op(0xe4, "cpx", "zero_page",   2, 3, seq,  false, true,  false),
  op(0xe5, "sbc", "zero_page",   2, 3, seq,  false, true,  false),
  op(0xe6, "inc", "zero_page",   2, 5, seq,  false, true,  true),
  op(0xe7, "isc", "zero_page",   2, 5, seq,  true,  true,  true),
  op(0xe8, "inx", "implied",     1, 2, seq,  false, false, false),
  op(0xe9, "sbc", "immediate",   2, 2, seq,  false, false, false),
  op(0xea, "nop", "implied",     1, 2, seq,  false, false, false),
  op(0xeb, "sbc", "immediate",   2, 2, seq,  true,  false, false),
  op(0xec, "cpx", "absolute",    3, 4, seq,  false, true,  false),
  op(0xed, "sbc", "absolute",    3, 4, seq,  false, true,  false),
  op(0xee, "inc", "absolute",    3, 6, seq,  false, true,  true),
  op(0xef, "isc", "absolute",    3, 6, seq,  true,  true,  true),

  // ========================== 0xF0-0xFF ==========================
  op(0xf0, "beq", "relative",    2, 2, br,   false, false, false),
  op(0xf1, "sbc", "indirect_y",  2, 5, seq,  false, true,  false),
  op(0xf2, "jam", "implied",     1, 0, halt, true,  false, false),
  op(0xf3, "isc", "indirect_y",  2, 8, seq,  true,  true,  true),
  op(0xf4, "nop", "zero_page_x", 2, 4, seq,  true,  true,  false),
  op(0xf5, "sbc", "zero_page_x", 2, 4, seq,  false, true,  false),
  op(0xf6, "inc", "zero_page_x", 2, 6, seq,  false, true,  true),
  op(0xf7, "isc", "zero_page_x", 2, 6, seq,  true,  true,  true),
  op(0xf8, "sed", "implied",     1, 2, seq,  false, false, false),
  op(0xf9, "sbc", "absolute_y",  3, 4, seq,  false, true,  false),
  op(0xfa, "nop", "implied",     1, 2, seq,  true,  false, false),
  op(0xfb, "isc", "absolute_y",  3, 7, seq,  true,  true,  true),
  op(0xfc, "nop", "absolute_x",  3, 4, seq,  true,  true,  false),
  op(0xfd, "sbc", "absolute_x",  3, 4, seq,  false, true,  false),
  op(0xfe, "inc", "absolute_x",  3, 7, seq,  false, true,  true),
  op(0xff, "isc", "absolute_x",  3, 7, seq,  true,  true,  true),
];
