// ============================================================================
// Known Symbols Database — static data module, not a pipeline step
// ============================================================================

export interface SymbolEntry {
  name: string;
  description: string;
  calling?: string;
}

export const KERNAL_SYMBOLS: Record<number, SymbolEntry> = {
  0xFF81: { name: "CINT", description: "Initialize screen editor", calling: "" },
  0xFF84: { name: "IOINIT", description: "Initialize I/O devices", calling: "" },
  0xFF87: { name: "RAMTAS", description: "Initialize RAM, set tape buffer", calling: "" },
  0xFF8A: { name: "RESTOR", description: "Restore default I/O vectors", calling: "" },
  0xFF8D: { name: "VECTOR", description: "Read/set vectored I/O", calling: "C=0: read, C=1: set; XY=table" },
  0xFF90: { name: "SETMSG", description: "Control KERNAL messages", calling: "A=message flag" },
  0xFF93: { name: "SECOND", description: "Send SA after LISTEN", calling: "A=secondary address" },
  0xFF96: { name: "TKSA", description: "Send SA after TALK", calling: "A=secondary address" },
  0xFF99: { name: "MEMTOP", description: "Read/set top of memory", calling: "C=0: read, C=1: set; XY=address" },
  0xFF9C: { name: "MEMBOT", description: "Read/set bottom of memory", calling: "C=0: read, C=1: set; XY=address" },
  0xFF9F: { name: "SCNKEY", description: "Scan keyboard", calling: "" },
  0xFFA2: { name: "SETTMO", description: "Set timeout for serial bus", calling: "A=timeout flag" },
  0xFFA5: { name: "ACPTR", description: "Input byte from serial bus", calling: "returns A" },
  0xFFA8: { name: "CIOUT", description: "Output byte to serial bus", calling: "A=byte" },
  0xFFAB: { name: "UNTLK", description: "Command serial bus UNTALK", calling: "" },
  0xFFAE: { name: "UNLSN", description: "Command serial bus UNLISTEN", calling: "" },
  0xFFB1: { name: "LISTEN", description: "Command serial bus LISTEN", calling: "A=device number" },
  0xFFB4: { name: "TALK", description: "Command serial bus TALK", calling: "A=device number" },
  0xFFB7: { name: "READST", description: "Read I/O status word", calling: "returns A" },
  0xFFBA: { name: "SETLFS", description: "Set logical file parameters", calling: "A=logical file, X=device, Y=secondary" },
  0xFFBD: { name: "SETNAM", description: "Set filename", calling: "A=length, XY=pointer" },
  0xFFC0: { name: "OPEN", description: "Open logical file", calling: "uses $B8-$BA" },
  0xFFC3: { name: "CLOSE", description: "Close logical file", calling: "A=logical file" },
  0xFFC6: { name: "CHKIN", description: "Open channel for input", calling: "X=logical file" },
  0xFFC9: { name: "CHKOUT", description: "Open channel for output", calling: "X=logical file" },
  0xFFCC: { name: "CLRCHN", description: "Close input/output channels", calling: "" },
  0xFFCF: { name: "CHRIN", description: "Input character from channel", calling: "returns A" },
  0xFFD2: { name: "CHROUT", description: "Output character to channel", calling: "A=character" },
  0xFFD5: { name: "LOAD", description: "Load from device", calling: "A=0:load,1:verify; XY=address" },
  0xFFD8: { name: "SAVE", description: "Save to device", calling: "A=ZP pointer; XY=end address" },
  0xFFDB: { name: "SETTIM", description: "Set system clock", calling: "AXY=time" },
  0xFFDE: { name: "RDTIM", description: "Read system clock", calling: "returns AXY" },
  0xFFE1: { name: "STOP", description: "Check STOP key", calling: "returns Z flag" },
  0xFFE4: { name: "GETIN", description: "Get character from keyboard buffer", calling: "returns A" },
  0xFFE7: { name: "CLALL", description: "Close all files and channels", calling: "" },
  0xFFEA: { name: "UDTIM", description: "Increment system clock", calling: "" },
  0xFFED: { name: "SCREEN", description: "Read screen size", calling: "returns X=cols, Y=rows" },
  0xFFF0: { name: "PLOT", description: "Read/set cursor position", calling: "C=0: read XY; C=1: set XY" },
  0xFFF3: { name: "IOBASE", description: "Read base of I/O area", calling: "returns XY=address" },
};

export const HARDWARE_SYMBOLS: Record<number, SymbolEntry> = {
  // VIC-II registers
  0xD000: { name: "VIC_SPR0_X", description: "Sprite 0 X position" },
  0xD001: { name: "VIC_SPR0_Y", description: "Sprite 0 Y position" },
  0xD002: { name: "VIC_SPR1_X", description: "Sprite 1 X position" },
  0xD003: { name: "VIC_SPR1_Y", description: "Sprite 1 Y position" },
  0xD004: { name: "VIC_SPR2_X", description: "Sprite 2 X position" },
  0xD005: { name: "VIC_SPR2_Y", description: "Sprite 2 Y position" },
  0xD006: { name: "VIC_SPR3_X", description: "Sprite 3 X position" },
  0xD007: { name: "VIC_SPR3_Y", description: "Sprite 3 Y position" },
  0xD008: { name: "VIC_SPR4_X", description: "Sprite 4 X position" },
  0xD009: { name: "VIC_SPR4_Y", description: "Sprite 4 Y position" },
  0xD00A: { name: "VIC_SPR5_X", description: "Sprite 5 X position" },
  0xD00B: { name: "VIC_SPR5_Y", description: "Sprite 5 Y position" },
  0xD00C: { name: "VIC_SPR6_X", description: "Sprite 6 X position" },
  0xD00D: { name: "VIC_SPR6_Y", description: "Sprite 6 Y position" },
  0xD00E: { name: "VIC_SPR7_X", description: "Sprite 7 X position" },
  0xD00F: { name: "VIC_SPR7_Y", description: "Sprite 7 Y position" },
  0xD010: { name: "VIC_SPR_XMSB", description: "Sprite X position MSBs" },
  0xD011: { name: "VIC_CTRL1", description: "Control register 1 (scroll Y, screen height, bitmap mode, DEN, raster MSB)" },
  0xD012: { name: "VIC_RASTER", description: "Raster line counter" },
  0xD013: { name: "VIC_LIGHT_X", description: "Light pen X" },
  0xD014: { name: "VIC_LIGHT_Y", description: "Light pen Y" },
  0xD015: { name: "VIC_SPR_ENABLE", description: "Sprite enable register" },
  0xD016: { name: "VIC_CTRL2", description: "Control register 2 (scroll X, screen width, multicolor)" },
  0xD017: { name: "VIC_SPR_YEXP", description: "Sprite Y expansion" },
  0xD018: { name: "VIC_MEM_PTR", description: "Memory pointers (screen base bits 4-7, charset bits 1-3)" },
  0xD019: { name: "VIC_IRQ", description: "Interrupt register (raster, sprite collision, lightpen)" },
  0xD01A: { name: "VIC_IRQ_ENABLE", description: "Interrupt enable register" },
  0xD01B: { name: "VIC_SPR_PRIORITY", description: "Sprite-to-background priority" },
  0xD01C: { name: "VIC_SPR_MULTICOLOR", description: "Sprite multicolor enable" },
  0xD01D: { name: "VIC_SPR_XEXP", description: "Sprite X expansion" },
  0xD01E: { name: "VIC_SPR_SPR_COLL", description: "Sprite-sprite collision (read clears)" },
  0xD01F: { name: "VIC_SPR_BG_COLL", description: "Sprite-background collision (read clears)" },
  0xD020: { name: "VIC_BORDER_COLOR", description: "Border color" },
  0xD021: { name: "VIC_BG_COLOR0", description: "Background color 0" },
  0xD022: { name: "VIC_BG_COLOR1", description: "Background color 1 (multicolor/ECM)" },
  0xD023: { name: "VIC_BG_COLOR2", description: "Background color 2 (multicolor/ECM)" },
  0xD024: { name: "VIC_BG_COLOR3", description: "Background color 3 (ECM)" },
  0xD025: { name: "VIC_SPR_MC0", description: "Sprite multicolor 0" },
  0xD026: { name: "VIC_SPR_MC1", description: "Sprite multicolor 1" },
  0xD027: { name: "VIC_SPR0_COLOR", description: "Sprite 0 color" },
  0xD028: { name: "VIC_SPR1_COLOR", description: "Sprite 1 color" },
  0xD029: { name: "VIC_SPR2_COLOR", description: "Sprite 2 color" },
  0xD02A: { name: "VIC_SPR3_COLOR", description: "Sprite 3 color" },
  0xD02B: { name: "VIC_SPR4_COLOR", description: "Sprite 4 color" },
  0xD02C: { name: "VIC_SPR5_COLOR", description: "Sprite 5 color" },
  0xD02D: { name: "VIC_SPR6_COLOR", description: "Sprite 6 color" },
  0xD02E: { name: "VIC_SPR7_COLOR", description: "Sprite 7 color" },

  // SID registers
  0xD400: { name: "SID_V1_FREQ_LO", description: "Voice 1 frequency low" },
  0xD401: { name: "SID_V1_FREQ_HI", description: "Voice 1 frequency high" },
  0xD402: { name: "SID_V1_PW_LO", description: "Voice 1 pulse width low" },
  0xD403: { name: "SID_V1_PW_HI", description: "Voice 1 pulse width high" },
  0xD404: { name: "SID_V1_CTRL", description: "Voice 1 control (waveform, gate, sync, ring, test)" },
  0xD405: { name: "SID_V1_AD", description: "Voice 1 attack/decay" },
  0xD406: { name: "SID_V1_SR", description: "Voice 1 sustain/release" },
  0xD407: { name: "SID_V2_FREQ_LO", description: "Voice 2 frequency low" },
  0xD408: { name: "SID_V2_FREQ_HI", description: "Voice 2 frequency high" },
  0xD409: { name: "SID_V2_PW_LO", description: "Voice 2 pulse width low" },
  0xD40A: { name: "SID_V2_PW_HI", description: "Voice 2 pulse width high" },
  0xD40B: { name: "SID_V2_CTRL", description: "Voice 2 control" },
  0xD40C: { name: "SID_V2_AD", description: "Voice 2 attack/decay" },
  0xD40D: { name: "SID_V2_SR", description: "Voice 2 sustain/release" },
  0xD40E: { name: "SID_V3_FREQ_LO", description: "Voice 3 frequency low" },
  0xD40F: { name: "SID_V3_FREQ_HI", description: "Voice 3 frequency high" },
  0xD410: { name: "SID_V3_PW_LO", description: "Voice 3 pulse width low" },
  0xD411: { name: "SID_V3_PW_HI", description: "Voice 3 pulse width high" },
  0xD412: { name: "SID_V3_CTRL", description: "Voice 3 control" },
  0xD413: { name: "SID_V3_AD", description: "Voice 3 attack/decay" },
  0xD414: { name: "SID_V3_SR", description: "Voice 3 sustain/release" },
  0xD415: { name: "SID_FILT_CUTOFF_LO", description: "Filter cutoff frequency low" },
  0xD416: { name: "SID_FILT_CUTOFF_HI", description: "Filter cutoff frequency high" },
  0xD417: { name: "SID_FILT_CTRL", description: "Filter resonance and routing" },
  0xD418: { name: "SID_FILT_VOL", description: "Filter mode and volume" },
  0xD419: { name: "SID_PADDLE_X", description: "Paddle X (read)" },
  0xD41A: { name: "SID_PADDLE_Y", description: "Paddle Y (read)" },
  0xD41B: { name: "SID_OSC3_RANDOM", description: "Voice 3 oscillator output (read)" },
  0xD41C: { name: "SID_ENV3", description: "Voice 3 envelope output (read)" },

  // CIA1 registers
  0xDC00: { name: "CIA1_PRA", description: "Data port A (keyboard column / joystick port 2)" },
  0xDC01: { name: "CIA1_PRB", description: "Data port B (keyboard row / joystick port 1)" },
  0xDC02: { name: "CIA1_DDRA", description: "Data direction register A" },
  0xDC03: { name: "CIA1_DDRB", description: "Data direction register B" },
  0xDC04: { name: "CIA1_TA_LO", description: "Timer A low byte" },
  0xDC05: { name: "CIA1_TA_HI", description: "Timer A high byte" },
  0xDC06: { name: "CIA1_TB_LO", description: "Timer B low byte" },
  0xDC07: { name: "CIA1_TB_HI", description: "Timer B high byte" },
  0xDC08: { name: "CIA1_TOD_10TH", description: "Time of day 1/10 seconds" },
  0xDC09: { name: "CIA1_TOD_SEC", description: "Time of day seconds" },
  0xDC0A: { name: "CIA1_TOD_MIN", description: "Time of day minutes" },
  0xDC0B: { name: "CIA1_TOD_HR", description: "Time of day hours" },
  0xDC0C: { name: "CIA1_SDR", description: "Serial data register" },
  0xDC0D: { name: "CIA1_ICR", description: "Interrupt control register" },
  0xDC0E: { name: "CIA1_CRA", description: "Control register A" },
  0xDC0F: { name: "CIA1_CRB", description: "Control register B" },

  // CIA2 registers
  0xDD00: { name: "CIA2_PRA", description: "Data port A (serial bus, VIC bank, RS-232)" },
  0xDD01: { name: "CIA2_PRB", description: "Data port B (user port)" },
  0xDD02: { name: "CIA2_DDRA", description: "Data direction register A" },
  0xDD03: { name: "CIA2_DDRB", description: "Data direction register B" },
  0xDD04: { name: "CIA2_TA_LO", description: "Timer A low byte" },
  0xDD05: { name: "CIA2_TA_HI", description: "Timer A high byte" },
  0xDD06: { name: "CIA2_TB_LO", description: "Timer B low byte" },
  0xDD07: { name: "CIA2_TB_HI", description: "Timer B high byte" },
  0xDD0D: { name: "CIA2_ICR", description: "Interrupt control register" },
  0xDD0E: { name: "CIA2_CRA", description: "Control register A" },
  0xDD0F: { name: "CIA2_CRB", description: "Control register B" },
};

export const COMPARISON_HINTS: Record<number, string> = {
  0x00: "null terminator / false",
  0x01: "1 / bit 0",
  0x03: "STOP key PETSCII",
  0x07: "bit position / direction (8 values)",
  0x08: "8 sprites / 8 bits",
  0x0D: "carriage return",
  0x0F: "color mask (0-15)",
  0x10: "16",
  0x14: "20",
  0x19: "25 (screen height)",
  0x1B: "27 / ESC",
  0x20: "space character (PETSCII)",
  0x28: "40 (screen width)",
  0x30: "ASCII '0'",
  0x39: "ASCII '9'",
  0x40: "64 (sprite size)",
  0x41: "ASCII 'A'",
  0x5A: "ASCII 'Z'",
  0x80: "bit 7 / high-bit marker",
  0xC0: "PETSCII shifted range start",
  0xFF: "all bits set / true / -1",
};

export function lookupSymbol(address: number): SymbolEntry | undefined {
  return KERNAL_SYMBOLS[address] || HARDWARE_SYMBOLS[address];
}

export function lookupComparisonHint(value: number): string | undefined {
  return COMPARISON_HINTS[value];
}
