// ============================================================================
// File Dependency Analyzer (pri 60) — cross-file dependency analysis
// ============================================================================

import type { IntegrationAnalyzer, IntegrationAnalyzerInput, IntegrationContribution } from "./types.js";

export class FileDependencyAnalyzer implements IntegrationAnalyzer {
  name = "file_dependency";
  priority = 60;

  analyze(input: IntegrationAnalyzerInput): IntegrationContribution {
    const { allBlocks } = input;

    // Generate overview documentation
    const totalBlocks = allBlocks.length;
    const codeBlocks = allBlocks.filter(b => b.category !== "data").length;
    const dataBlocks = totalBlocks - codeBlocks;

    const highConfidence = allBlocks.filter(b => b.confidence >= 0.8).length;
    const medConfidence = allBlocks.filter(b => b.confidence >= 0.5 && b.confidence < 0.8).length;
    const lowConfidence = allBlocks.filter(b => b.confidence < 0.5).length;

    // File headers based on categories
    const fileHeaders: Record<string, string> = {};
    const categories = new Set(allBlocks.map(b => b.category));
    for (const cat of categories) {
      const catBlocks = allBlocks.filter(b => b.category === cat);
      fileHeaders[`${cat}.asm`] = [
        `; ${cat}.asm — ${catBlocks.length} blocks`,
        `; Auto-generated by RE pipeline`,
      ].join("\n");
    }

    return {
      section: "overviewComments",
      data: {
        fileHeaders,
        summary: {
          totalBlocks,
          codeBlocks,
          dataBlocks,
          confidenceDistribution: {
            high: highConfidence,
            medium: medConfidence,
            low: lowConfidence,
          },
        },
      },
    };
  }
}
