// C64 Memory Map Symbols
// Extracted from 'Mapping the Commodore 64' by Sheldon Leemon
// Multi-byte locations: use SYMBOL+1, SYMBOL+2 etc. for subsequent bytes
// See c64_address_map.asm for the complete address-to-symbol lookup
//

// === Zero Page ($00-$FF) ===

.const D6510         = $0
.const R6510         = $1
.const ADRAY1        = $3  // 2 bytes
.const ADRAY2        = $5  // 2 bytes
.const CHARAC        = $7
.const ENDCHR        = $8
.const TRMPOS        = $9
.const VERCK_A       = $A
.const COUNT         = $B
.const DIMFLG        = $C
.const VALTYP        = $D
.const INTFLG        = $E
.const GARBFL        = $F
.const SUBFLG        = $10
.const INPFLG        = $11
.const TANSGN        = $12
.const CHANNL        = $13
.const LINNUM        = $14  // 2 bytes
.const TEMPPT        = $16
.const LASTPT        = $17  // 2 bytes
.const TEMPST        = $19  // 9 bytes
.const INDEX         = $22  // 4 bytes
.const RESHO         = $26  // 5 bytes
.const TXTTAB        = $2B  // 2 bytes
.const VARTAB        = $2D  // 2 bytes
.const ARYTAB        = $2F  // 2 bytes
.const STREND        = $31  // 2 bytes
.const FREETOP       = $33  // 2 bytes
.const FRESPC        = $35  // 2 bytes
.const MEMSIZ        = $37  // 2 bytes
.const CURLIN        = $39  // 2 bytes
.const OLDLIN        = $3B  // 2 bytes
.const OLDTXT        = $3D  // 2 bytes
.const DATLIN        = $3F  // 2 bytes
.const DATPTR        = $41  // 2 bytes
.const INPPTR        = $43  // 2 bytes
.const VARNAM        = $45  // 2 bytes
.const VARPNT        = $47  // 2 bytes
.const FORPNT        = $49  // 2 bytes
.const OPPTR         = $4B  // 2 bytes
.const OPMASK        = $4D
.const DEFPNT        = $4E  // 2 bytes
.const DSCPNT        = $50  // 3 bytes
.const FOUR6         = $53
.const JMPER         = $54  // 3 bytes
.const FAC1          = $61  // 6 bytes
.const FACEXP        = $61
.const FACHO         = $62  // 4 bytes
.const FACSGN        = $66
.const SGNFLG        = $67
.const BITS          = $68
.const FAC2          = $69  // 6 bytes
.const ARGEXP        = $69
.const ARGHO         = $6A  // 4 bytes
.const ARGSGN        = $6E
.const ARISGN        = $6F
.const FACOV         = $70
.const FBUFPT        = $71  // 2 bytes
.const CHRGET        = $73  // 24 bytes
.const RNDX          = $8B  // 5 bytes
.const STATUS        = $90
.const STKEY         = $91
.const SVXT          = $92
.const VERCK_93      = $93
.const C3PO          = $94
.const BSOUR         = $95
.const SYNO          = $96
.const XSAV          = $97
.const LDTND         = $98
.const DFLTN         = $99
.const DFLTO         = $9A
.const PRTY          = $9B
.const DPSW          = $9C
.const MSGFLG        = $9D
.const PTR1          = $9E
.const PTR2          = $9F
.const TIME          = $A0  // 3 bytes
.const CNTDN         = $A5
.const BUFPNT        = $A6
.const INBIT         = $A7
.const BITCI         = $A8
.const RINONE        = $A9
.const RIDATA        = $AA
.const RIPRTY        = $AB
.const SAL           = $AC  // 2 bytes
.const EAL           = $AE  // 2 bytes
.const CMP0          = $B0  // 2 bytes
.const TAPE1         = $B2  // 2 bytes
.const BITTS         = $B4
.const NXTBIT        = $B5
.const RODATA        = $B6
.const FNLEN         = $B7
.const LA            = $B8
.const SA            = $B9
.const FA            = $BA
.const FNADR         = $BB  // 2 bytes
.const ROPRTY        = $BD
.const FSBLK         = $BE
.const MYCH          = $BF
.const CAS1          = $C0
.const STAL          = $C1  // 2 bytes
.const LSTX          = $C5
.const NDX           = $C6
.const RVS           = $C7
.const INDX          = $C8
.const LXSP          = $C9  // 2 bytes
.const SFDX          = $CB
.const BLNSW         = $CC
.const BLNCT         = $CD
.const GDBLN         = $CE
.const BLNON         = $CF
.const CRSW          = $D0
.const PNT           = $D1  // 2 bytes
.const PNTR          = $D3
.const QTSW          = $D4
.const LNMX          = $D5
.const TBLX          = $D6
.const INSRT         = $D8
.const LDTB1         = $D9  // 26 bytes
.const USER          = $F3  // 2 bytes
.const KEYTAB        = $F5  // 2 bytes
.const RIBUF         = $F7  // 2 bytes
.const ROBUF         = $F9  // 2 bytes
.const FREEZP        = $FB  // 4 bytes
.const BASZPT        = $FF
.const TO            = $A4
.const FN            = $A5
.const THEN          = $A7
.const NOT           = $A8
.const STEP          = $A9

// === Page 1 ($100-$1FF) - Processor Stack ===

.const BAD           = $100  // 63 bytes

// === Pages 2-3 ($200-$3FF) - OS Working Storage ===

.const BUF           = $200  // 89 bytes
.const LAT           = $259  // 10 bytes
.const FAT           = $263  // 10 bytes
.const SAT           = $26D  // 10 bytes
.const KEYD          = $277  // 10 bytes
.const TIMOUT        = $285
.const COLOR         = $286
.const GDCOL         = $287
.const HIBASE        = $288
.const XMAX          = $289
.const RPTFLAG       = $28A
.const KOUNT         = $28B
.const DELAY         = $28C
.const SHFLAG        = $28D
.const LSTSHF        = $28E
.const KEYLOG        = $28F  // 2 bytes
.const MODE          = $291
.const AUTODN        = $292
.const M51CTR        = $293
.const M51CDR        = $294
.const M51AJB        = $295  // 2 bytes
.const BITNUM        = $298
.const BAUDOF        = $299  // 2 bytes
.const RIDBE         = $29B
.const RIDBS         = $29C
.const RODBS         = $29D
.const RODBE         = $29E
.const IRQTMP        = $29F  // 2 bytes
.const ENABL         = $2A1
.const IERROR        = $300  // 2 bytes
.const IMAIN         = $302  // 2 bytes
.const ICRNCH        = $304  // 2 bytes
.const IQPLOP        = $306  // 2 bytes
.const IGONE         = $308  // 2 bytes
.const IEVAL         = $30A  // 2 bytes
.const SAREG         = $30C
.const SXREG         = $30D
.const SYREG         = $30E
.const SPREG         = $30F
.const USRPOK        = $310
.const USRADD        = $311  // 2 bytes
.const CINV          = $314  // 2 bytes
.const CBINV         = $316  // 2 bytes
.const NMINV         = $318  // 2 bytes
.const IOPEN         = $31A  // 2 bytes
.const ICLOSE        = $31C  // 2 bytes
.const ICHKIN        = $31E  // 2 bytes
.const ICKOUT        = $320  // 2 bytes
.const ICLRCH        = $322  // 2 bytes
.const IBASIN        = $324  // 2 bytes
.const IBSOUT        = $326  // 2 bytes
.const ISTOP         = $328  // 2 bytes
.const IGETIN        = $32A  // 2 bytes
.const ICLALL        = $32C  // 2 bytes
.const USRCMD        = $32E  // 2 bytes
.const ILOAD         = $330  // 2 bytes
.const ISAVE         = $332  // 2 bytes
.const TBUFFER       = $33C  // 192 bytes

// === Screen Memory & BASIC Text ($400-$9FFF) ===

.const VICSCN        = $400  // 1024 bytes
.const SETTMO        = $E21

// === BASIC ROM ($A000-$BFFF) ===

.const STMDSP        = $A00C
.const FUNDSP        = $A052  // 46 bytes
.const OPTAB         = $A080  // 30 bytes
.const RESLST        = $A09E  // 256 bytes
.const ERRTAB        = $A19E  // 394 bytes
.const FNDFOR        = $A38A  // 46 bytes
.const BLTU          = $A3B8
.const GETSTK        = $A3FB  // 13 bytes
.const REASON        = $A408  // 45 bytes
.const OMERR         = $A435  // 52 bytes
.const ERROR         = $A437  // 50 bytes
.const READY         = $A474  // 11 bytes
.const MAIN          = $A480  // 28 bytes
.const MAIN1         = $A49C
.const LINKPRG       = $A533
.const INLIN         = $A560
.const CRUNCH        = $A579
.const FINDLN        = $A613
.const SCRTCH        = $A642
.const CLEAR         = $A65E
.const RUNC          = $A68E
.const LIST          = $A69C
.const QPLOP         = $A717
.const FOR           = $A742
.const NEWSTT        = $A7AE
.const GONE          = $A7E4
.const RESTOR_BASIC  = $A81D
.const END           = $A831
.const CONT          = $A857
.const RUN           = $A871
.const GOSUB         = $A883
.const GOTO          = $A8A0
.const RETURN        = $A8D2
.const DATA          = $A8F8
.const DATAN         = $A906
.const IF            = $A928
.const REM           = $A93B
.const ONGOTO        = $A94B
.const LINGET        = $A96B
.const LET           = $A9A5
.const PRINTN        = $AA80
.const CMD           = $AA86
.const PRINT         = $AAA0
.const STROUT        = $AB1E
.const DOAGIN        = $AB4D
.const GET           = $AB7B
.const INPUTN        = $ABA5
.const INPUT         = $ABBF
.const READ          = $AC06
.const EXIGNT        = $ACFC
.const NEXT          = $AD1E
.const FRMNUM        = $AD8A
.const FRMEVAL       = $AD9E
.const EVAL          = $AE83
.const PIVAL         = $AEA8
.const PARCHK        = $AEF1
.const CHKCLS        = $AEF7
.const CHKOPN        = $AEFA
.const CHKCOM        = $AEFF
.const SNERR         = $AF08
.const ISVAR         = $AF2B
.const ISFUN         = $AFA7
.const OROP          = $AFE6
.const ANDOP         = $AFE9
.const DORE1         = $B016
.const DIM           = $B018
.const PTRGET        = $B08B
.const NOTFNS        = $B11D
.const FINPTR        = $B185
.const ARYGET        = $B194
.const N32768        = $B1A5
.const INTIDX        = $B1B2
.const AYINT         = $B1BF
.const ISARY         = $B1D1
.const BSERR         = $B245
.const FCERR         = $B248
.const UMULT         = $B34C
.const FRE           = $B37D
.const GIVAYF        = $B391
.const POS           = $B39E
.const ERRDIR        = $B3A6
.const DEF           = $B3B3
.const GETFNM        = $B3E1
.const FNDOER        = $B3F4
.const STRD          = $B465
.const STRLIT        = $B487
.const GETSPA        = $B4F4
.const GARBAG        = $B526
.const CAT           = $B63D
.const MOVINS        = $B67A
.const FRESTR        = $B6A3
.const FRETMS        = $B6DB
.const CHRD          = $B6EC
.const LEFTD         = $B700
.const RIGHTD        = $B72C
.const MIDD          = $B737
.const PREAM         = $B761
.const LEN           = $B77C
.const ASC           = $B78B
.const GETBYTC       = $B79B
.const VAL           = $B7AD
.const GETNUM        = $B7EB
.const GETADR        = $B7F7
.const PEEK          = $B80D
.const POKE          = $B824
.const FUWAIT        = $B82D
.const FADDH         = $B849
.const FSUB          = $B850
.const FSUBT         = $B853
.const FADD          = $B867
.const FADDT         = $B86A
.const FADD4         = $B8A7
.const NORMAL        = $B8FE
.const NEGFAC        = $B947
.const OVERR         = $B97E
.const MULSHF        = $B983
.const FONE          = $B9BC
.const LOGCN2        = $B9C1
.const LOG           = $B9EA
.const FMULT         = $BA28
.const MLTPLY        = $BA59
.const CONUPK        = $BA8C
.const MULDIV        = $BAB7
.const MLDVEX        = $BAD4
.const MUL10         = $BAE2
.const TENC          = $BAF9
.const DIV10         = $BAFE
.const FDIV          = $BB0F
.const FDIVT         = $BB12
.const MOVFM         = $BBA2
.const MOV2F         = $BBC7
.const MOVFA         = $BBFC
.const MOVAF         = $BC0C
.const MOVEF         = $BC0F
.const ROUND         = $BC1B
.const SIGN          = $BC2B
.const SGN           = $BC39
.const ABS           = $BC58
.const FCOMP         = $BC5B
.const QINT          = $BC9B
.const INT           = $BCCC
.const FIN           = $BCF3
.const FINLOG        = $BD7E
.const NO999         = $BDB3
.const INPRT         = $BDC0
.const LINPRT        = $BDCD
.const FOUT          = $BDDD
.const FHALF         = $BF11
.const FOUTBL        = $BF1C
.const FDCEND        = $BF3A
.const SQR           = $BF71
.const FPWRT         = $BF7B
.const NEGOP         = $BFB4
.const EXPCON        = $BFBF
.const EXP           = $BFED

// === VIC-II Registers ($D000-$D3FF) ===

.const SP0X          = $D000
.const SP0Y          = $D001
.const SP1X          = $D002
.const SP1Y          = $D003
.const SP2X          = $D004
.const SP2Y          = $D005
.const SP3X          = $D006
.const SP3Y          = $D007
.const SP4X          = $D008
.const SP4Y          = $D009
.const SP5X          = $D00A
.const SP5Y          = $D00B
.const SP6X          = $D00C
.const SP6Y          = $D00D
.const SP7X          = $D00E
.const SP7Y          = $D00F
.const MSIGX         = $D010
.const SCROLY        = $D011
.const RASTER        = $D012
.const LPENX         = $D013
.const LPENY         = $D014
.const SPENA         = $D015
.const SCROLX        = $D016
.const YXPAND        = $D017
.const VMCSB         = $D018
.const VICIRQ        = $D019
.const IRQMASK       = $D01A
.const SPBGPR        = $D01B
.const SPMC          = $D01C
.const XXPAND        = $D01D
.const SPSPCL        = $D01E
.const SPBGCL        = $D01F
.const EXTCOL        = $D020
.const BGCOL0        = $D021
.const BGCOL1        = $D022
.const BGCOL2        = $D023
.const BGCOL3        = $D024
.const SPMC0         = $D025
.const SPMC1         = $D026
.const SP0COL        = $D027
.const SP1COL        = $D028
.const SP2COL        = $D029
.const SP3COL        = $D02A
.const SP4COL        = $D02B
.const SP5COL        = $D02C
.const SP6COL        = $D02D
.const SP7COL        = $D02E

// === SID Registers ($D400-$D7FF) ===

.const FRELO1        = $D400
.const FREHI1        = $D401
.const PWLO1         = $D402
.const PWHI1         = $D403
.const VCREG1        = $D404
.const ATDCY1        = $D405
.const SUREL1        = $D406
.const FRELO2        = $D407
.const FREHI2        = $D408
.const PWLO2         = $D409
.const PWHI2         = $D40A
.const VCREG2        = $D40B
.const ATDCY2        = $D40C
.const SUREL2        = $D40D
.const FRELO3        = $D40E
.const FREHI3        = $D40F
.const PWLO3         = $D410
.const PWHI3         = $D411
.const VCREG3        = $D412
.const ATDCY3        = $D413
.const SUREL3        = $D414
.const CUTLO         = $D415
.const CUTHI         = $D416
.const RESON         = $D417
.const SIGVOL        = $D418
.const POTX          = $D419
.const POTY          = $D41A
.const RANDOM        = $D41B
.const ENV3          = $D41C

// === CIA 1 ($DC00-$DC0F) ===

.const CIAPRA        = $DC00
.const CIAPRB        = $DC01
.const CIDDRA        = $DC02
.const CIDDRB        = $DC03
.const TIMALO        = $DC04
.const TIMAHI        = $DC05
.const TIMBLO        = $DC06
.const TIMBHI        = $DC07
.const TODTEN        = $DC08
.const TODSEC        = $DC09
.const TODMIN        = $DC0A
.const TODHRS        = $DC0B
.const CIASDR        = $DC0C
.const CIAICR        = $DC0D
.const CIACRA        = $DC0E
.const CIACRB        = $DC0F

// === CIA 2 ($DD00-$DD0F) ===

.const CI2PRA        = $DD00
.const CI2PRB        = $DD01
.const C2DDRA        = $DD02
.const C2DDRB        = $DD03
.const TI2ALO        = $DD04
.const TI2AHI        = $DD05
.const TI2BLO        = $DD06
.const TI2BHI        = $DD07
.const TO2TEN        = $DD08
.const TO2SEC        = $DD09
.const TO2MIN        = $DD0A
.const TO2HRS        = $DD0B
.const CI2SDR        = $DD0C
.const CI2ICR        = $DD0D
.const CI2CRA        = $DD0E
.const CI2CRB        = $DD0F

// === KERNAL ROM ($E000-$FFFF) ===

.const POLY1         = $E043
.const POLY2         = $E059
.const RMULC         = $E08D
.const RADDC         = $E092
.const RND           = $E097
.const SYS           = $E12A
.const SAVE_E156     = $E156
.const VERIFY        = $E165
.const LOAD_E168     = $E168
.const OPEN_E1BE     = $E1BE
.const CLOSE_E1C7    = $E1C7
.const COS           = $E264
.const SIN           = $E268
.const TAN           = $E2B4
.const PI2           = $E2E0
.const TWOPI         = $E2E5
.const FR4           = $E2EA
.const SINCON        = $E2EF
.const ATN           = $E30E
.const ATNCON        = $E33E
.const INITAT        = $E3A2
.const INIT          = $E3BF
.const WORDS         = $E460
.const IOBASE        = $E500
.const SCREEN        = $E505
.const PLOT          = $E50A
.const LP2           = $E5B4
.const SCNKEY        = $EA87
.const TALK          = $ED09
.const LISTEN        = $ED0C
.const SECOND        = $EDB9
.const TKSA          = $EDC7
.const CIOUT         = $EDDD
.const UNTLK         = $EDEF
.const UNLSN         = $EDFE
.const ACPTR         = $EE13
.const GETIN         = $F13E
.const CHRIN         = $F157
.const CHROUT        = $F1CA
.const CHKIN         = $F20E
.const CHKOUT        = $F250
.const CLOSE_F291    = $F291
.const CLALL         = $F32F
.const CLRCHN        = $F333
.const OPEN_F34A     = $F34A
.const LOAD_F49E     = $F49E
.const SAVE_F5DD     = $F5DD
.const UDTIM         = $F69B
.const RDTIM         = $F6DD
.const SETTIM        = $F6E4
.const STOP          = $F6ED
.const RESTOR_KERNAL = $FD15
.const VECTOR        = $FD1A
.const RAMTAS        = $FD50
.const IOINIT        = $FDA3
.const SETNAM        = $FDF9
.const SETLFS        = $FE00
.const READST        = $FE07
.const SETMSG        = $FE18
.const MEMTOP        = $FE25
.const MEMBOT        = $FE34
.const CINT          = $FF5B
